version: "3"
services:
    grafana:
        image: grafana/grafana
        ports:
            - "3000:3000"
        volumes: 
            - "grafana-data:/var/lib/grafana"
            - "./grafana-config:/usr/app/config"
        environment: 
            GF_PATHS_CONFIG: "/usr/app/config/grafana.ini"
    graphite:
        image: graphiteapp/graphite-statsd
        ports: 
            - "80:80"
            - "2003:2003"
            - "2004:2004"
            - "2023:2023"
            - "2024:2024"
            - "8125:8125/udp"
            - "8126:8126"
volumes:
    grafana-data: